In [2]:
from run_msa3d import *

In [3]:
# RUN THE PIPELINE ONLY PARTLY

# run_process = False --> skip running stage 2/3 set 
# run_postprocess = True --> run postprocessing
# run_cubebuild = True --> run cube_build

# provide own paths to data and msa
# data_entries : path to 2D spectra
# msa_path : path to MSA
data_entries = np.sort(glob.glob('/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp*nobar/newoutput*_s2d.fits')) 
msa_path = '/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/jw02136001001_01_msa.fits'

run(data_entries, msa_path, run_process=False, run_postprocess=True, run_cubebuild=True)

/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_03101_nobar
running postprocessing
31
59 /Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_0311r_nobar/newoutput_s00001_s2d.fits
/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_0311r_nobar/newoutput_s02111_s2d.fits 2111
[1.28047663 1.28044421 1.28041179 ... 1.30736325 1.30740529 1.30744732] True
/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_0311r_nobar/newoutput_s02145_s2d.fits 2145
[1.28047518 1.28044275 1.28041033 ... 1.31255929 1.31260135 1.31264155] True
/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_0311r_nobar/newoutput_s02465_s2d.fits 2465
[1.28048143 1.28044901 1.2804166  ... 1.31257067 1.31261274 1.31265481] True
/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/reduction/process/exp_0311r_nobar/newoutput_s02824_s2d.fits 2824
[1.2804763  1.28044389 1.28041148 ... 1.31254206 1.3125841  1.31262614] True
/Users/ibarisic/Downl

KeyboardInterrupt: 

In [ ]:
# RUN FULL PIPELINE

# run_process = False --> skip running stage 2/3 set 
# run_postprocess = True --> run postprocessing
# run_cubebuild = True --> run cube_build

# provide own paths to data and msa
# data_entries : path to rate files
# msa_path : path to MSA
data_entries = np.sort(glob.glob('/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/jw*rate.fits')) 
msa_path = '/Users/ibarisic/Downloads/GO_2136_ALL_DATA/JWST/jw02136001001_01_msa.fits'

run(data_entries, msa_path, run_process=True, run_postprocess=True, run_cubebuild=True)